### ISSUE TITLE
Support AWS deployment type

### ISSUE THREAD

**Issue by loyaltyarm** [sharetribe/ftw-hourly#114]
From the documentation, the only production environment supported for deployment is Heroku. Our organization only runs its applications and data infrastructure in AWS and would prefer to host there. Can the team outline hosting instructions for AWS environments? There is no preference to what AWS services would be used to host the application.

**Comment by Gnito** [comment]
@loyaltyarm, unfortunately, we don't have currently any guide about AWS setup specifically. I'll add this to our feature request tracking system.

However, FTW templates are normal NodeJS/Express applications. You need to provide some environment variables to them, but that's pretty much the only requirement for any [production environment](https://www.sharetribe.com/docs/ftw-hosting/how-to-deploy-ftw-to-production/#getting-started). 

So, from that perspective, there are no FTW-specific requirements - it's about running NodeJS application there. I haven't personally tried to run it in AWS stack, but what I've understood AWS ElasticBeanstalk is probably the easiest way to get production-like setup for a generic Node app. 

Side note: it seems that there are some issues reported about memory need with Node.js apps (e.g. here's one [old article I came across earlier](https://medium.com/@deanslamajr/an-insufficient-memory-deployment-failure-d9f1cb9b5c0#a5bf)) - but it probably depends on your deploy/build orchestration if you encounter them.

**Comment by loyaltyarm** [comment]
Thanks for the consideration and helpful links. I'm going to give this a go and will document steps in more detail than the other resources I've found so there is something to build from here. Should we leave this issue open to capture those notes?

**Comment by Gnito** [comment]
Closing this thread, since it's been inactive.
