### ISSUE TITLE
Calendar entries are lost after changing month

### ISSUE THREAD

**Issue by ugened47** [sharetribe/ftw-hourly#165]
Calendar entries are lost after the calendar inside `FieldDateAndTimeInput` is closed and it's unavailable to select date/time.

**To Reproduce** Steps to reproduce the behavior:

1. Go to the listing page
2. Click on calendar input click next month arrow and select date.
3. Calendar is closed and no time entries are available
4. Open calendar again and no dates are available

**Expected behavior**
Calendar works correctly

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="1014" alt="Screenshot 2021-08-23 at 20 20 16" src="https://user-images.githubusercontent.com/9214135/130490046-9e4d0410-145e-4c08-aa97-8e06a30e0c78.png">

<img width="703" alt="Screenshot 2021-08-23 at 20 20 51" src="https://user-images.githubusercontent.com/9214135/130490147-f706e41b-5363-4535-a255-4c33ff1b4175.png">

<img width="700" alt="Screenshot 2021-08-23 at 20 21 01" src="https://user-images.githubusercontent.com/9214135/130490156-98b3eb20-57f8-4fea-8107-1bce8ecd91cb.png">

**Additional context**
Only happens when changing the month. The `currentMonth` is reset before it's actually used inside `onBookingStartDateChanged` callback.

When removed onClose prop introduced in https://github.com/sharetribe/ftw-hourly/pull/158 everything started working correctly.

**Comment by Gnito** [comment]
Thanks for the report and sorry, our focus has been a bit elsewhere - so, we missed this earlier. 

Bug fix is now merged to master.
