### ISSUE TITLE
When changing the month in the ftw-hourly template on booking, there are no timeslot options available to select even if there is availability on those days

### ISSUE THREAD

**Issue by Basitowaisi** [sharetribe/ftw-hourly#174]
**In ftw-hourly template when you go to the listing page, you click on the calendar and change the month in the calendar and select a date from that changed month, you won't get to see any of the timeslots. I debugged the issue and found out that the currentMonth was resetting to the original current month not to the changed one.

**To Reproduce** 
1. Go to 'Listing Page'
2. Click on 'Date Picker', where you get to select the booking date,
3. Change the month.
4. Select a date from the changed month.
5. You will see that you won't get to see any timeslots in that particular day, even if there were.
6. This is because the currentMonth in the state is resetting to original current month not to the changed one.
7. This is all happening because of new onClose function passed to the date component.

Here i clicked on the calendar and changed the month to december
<img width="1440" alt="Screenshot 2021-11-11 at 12 44 07 PM" src="https://user-images.githubusercontent.com/23507477/141255171-b64f4f9f-7847-4d1e-a884-20b6d0439c12.png">

Here i selected the date from the month december and i didn't got any slots to select from.
As you can clearly see what the problem is, the currentmonth is resetting to old current month.

<img width="1440" alt="Screenshot 2021-11-11 at 12 44 21 PM" src="https://user-images.githubusercontent.com/23507477/141255181-5022926c-7962-49d8-8f70-b8a72dea72f6.png">

This is what IMO causes the issue.
<img width="859" alt="Screenshot 2021-11-11 at 12 46 17 PM" src="https://user-images.githubusercontent.com/23507477/141255225-5c39411f-6a89-4c1b-bad8-b97265272ec9.png">

Also all calendar days are disabled because of wrong month in the state.
<img width="1436" alt="Screenshot 2021-11-11 at 1 05 59 PM" src="https://user-images.githubusercontent.com/23507477/141257587-30eaa521-bb9a-44da-9126-f70743b01c0a.png">

**Expected behavior** 
When you change the month, the timeslots of that changed month should have appeared so that the user can select from those as per his need.

**Solution**
I have also found a solution to the problem. If you allow me I may present my solution. 

Currently I am using MacOS, I have faced the same issue when i was using a linux based machine.

**Comment by Gnito** [comment]
Thanks for the report and accompanied pull request - and sorry, our focus has been a bit elsewhere - so, we missed this earlier. 

The bug fix is now been merged to master.
